name: Reusable workflow example

on:
  workflow_call:
    inputs:
      config-path:
        required: true
        type: string
    secrets:
      test-key:
        required: true
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - uses: actions/checkout@v4
    - name: Hello World
      run: |
          echo "hello world,hello-workflow1, secrets test-key:${{ secrets.test-key }}, inputs config-path:${{ inputs.config-path }}"
